#name, main, version and api are required
name: DonateInfo
main: DonateInfo\DonateInfo
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.0"]

author: NycuRO
description: Show permision of ranks. For my server.
commands:
  membru:
    description: Arata permisiile rankului Membru
    usage: "/membru"
    permission: nycuro.membru
  membru+:
    description: Arata permisiile rankului Membru+
    usage: "/membru+"
    permission: nycuro.membruplus
  vip:
    description: Arata permisiile rankului VIP
    usage: "/vip"
    permission: nycuro.vip
  moderator:
    description: Arata permisiile rankului Moderator
    usage: "/moderator"
    permission: nycuro.moderator
  moderator+:
    description: Arata permisiile rankului Moderator+
    usage: "/moderator+"
    permission: nycuro.moderatorplus
  manager:
    description: Arata permisiile rankului Manager
    usage: "/manager"
    permission: nycuro.manager
  yt:
    description: Arata permisiile rankului YT
    usage: "/yt"
    permission: nycuro.yt
  helperjr:
    description: Arata permisiile rankului HelperJr
    usage: "/helperjr"
    permission: nycuro.helperjr
  helper:
    description: Arata permisiile rankului Helper
    usage: "/helper"
    permission: nycuro.helper
permissions:
  nycuro.membru:
    description: "Arata permisiile rankului Membru"
    default: true
  nycuro.membruplus:
    description: "Arata permisiile rankului Membru+"
    default: true
  nycuro.vip:
    description: "Arata permisiile rankului VIP"
    default: true
  nycuro.moderator:
    description: "Arata permisiile rankului Moderator"
    default: true
  nycuro.moderatorplus:
    description: "Arata permisiile rankului Moderator+"
    default: true
  nycuro.manager:
    description: "Arata permisiile rankului Manager"
    default: true
  nycuro.helperjr:
    description: "Arata permisiile rankului HelperJr"
    default: true
  nycuro.yt:
    description: "Arata permisiile rankului YT"
    default: true
  nycuro.helper:
    description: "Arata permisiile rankului Helper"
    default: true
